### ISSUE TITLE
Integration with Endurain

### ISSUE THREAD

**Issue by joaovitoriasilva** [jonasoreland/runnerup#1185]
Hello,

I am the developer of Endurain, a self hosted fitness service. Right now the service allows the user to import activities using GPX upload or by linking Strava.

A potential user of Endurain identified your app as a great app and highlighted the use case of when an activity is recorded in your app it could be automatically imported to his/hers Endurain instance. 

Is this something you maybe be willing to implement? If yes could you reach out to me to discuss further detail?

Link to Endurain repo: https://github.com/joaovitoriasilva/endurain

Thank you

**Comment by AquaWolf** [comment]
I would like to get deeper into RunnerUp but I'm not sure if this repo is still actively maintained. @jonasoreland  If I would make a PR would it be possible to merge this to main and publish it to the play store?

**Comment by gerhardol** [comment]
It is maintained. @jonasoreland is mostly not involved, I have maintained since 2017 (also Play since 2020).
But there has not been many features added for some years. Number of users have been quite stable the last years, around 4000.
(I am not a big user myself, another maintainer is welcome. I want an open source alternative, not planning to give up.)

**Comment by AquaWolf** [comment]
@joaovitoriasilva is there already an API I could use with user authentication for endurain? If yes, does a swagger file or postman collection exist? Or can you point me to some files where an activity can be created by an API call? Thanks in advance.

**Comment by joaovitoriasilva** [comment]
Hello @AquaWolf yes there is currently only one endpoint that enables activity upload using a GPX file. In the queue is also FIT files to be implemented. 

I can also make available other endpoints with different logic to better support this if needed.

I am almost pushing a new version (0.3.0 probably next week) that will have some changes on the login structure and logic to better handle 3rd party apps like this one.

I also plan to make a instance public so everyone can check API docs and etc to make this easier. Also some overall docs for the service are also needed.

Is there a better way we can chat and talk about this?

**Comment by joaovitoriasilva** [comment]
Hello again, the new version is out with the foundations for this. More info here: https://github.com/joaovitoriasilva/endurain?tab=readme-ov-file#integrate-with-your-application

What can I do to further help you?

**Comment by gerhardol** [comment]
> What can I do to further help you?

No look at details, just some comments.
Is this a refresh token? (There is such an implementation in at least runalyze and Strava so this could be a copy&paste implementation - most code is shared already).

Any details for .gpx extensions? Laps, hr and cadence is not supported by default. This is why .tcx is used normally. There are no plans to support .fit in RU. The requirements for the .fit lib is that it must be manually downloaded from ant and automated builds are not possible (and an implementation from the source is too much job)..

**Comment by AquaWolf** [comment]
Yeha I will do the copy paste job probably on Sunday and will give it a try and come back to you if I have some questions or blocker 😃

**Comment by joaovitoriasilva** [comment]
Yes, the endpoint returns an access token (short lived) and a refresh token (long lived).

For the gpx extensions the backend is able to parse some of them like hr, power and cadence.

I can look to .tcx extension as well if it makes sense

**Comment by AquaWolf** [comment]
I'm trying to setup the endurain docker-compose stack and it looks like the backend is not able to connect to the mariadb:
```
backend       |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
backend       |     self._dbapi_connection = engine.raw_connection()
backend       |                              ^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3300, in raw_connection
backend       |     return self.pool.connect()
backend       |            ^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
backend       |     return _ConnectionFairy._checkout(self)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
backend       |     fairy = _ConnectionRecord.checkout(pool)
backend       |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
backend       |     rec = pool._do_get()
backend       |           ^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
backend       |     with util.safe_reraise():
backend       |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
backend       |     raise exc_value.with_traceback(exc_tb)
backend       |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
backend       |     return self._create_connection()
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
backend       |     return _ConnectionRecord(self)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
backend       |     self.__connect()
backend       |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
backend       |     with util.safe_reraise():
backend       |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
backend       |     raise exc_value.with_traceback(exc_tb)
backend       |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
backend       |     self.dbapi_connection = connection = pool._invoke_creator(self)
backend       |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 643, in connect
backend       |     return dialect.connect(*cargs, **cparams)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 620, in connect
backend       |     return self.loaded_dbapi.connect(*cargs, **cparams)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/MySQLdb/__init__.py", line 121, in Connect
backend       |     return Connection(*args, **kwargs)
backend       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend       |   File "/usr/local/lib/python3.12/site-packages/MySQLdb/connections.py", line 195, in __init__
backend       |     super().__init__(*args, **kwargs2)
backend       | MySQLdb.OperationalError: (2002, "Can't connect to server on 'mariadb' (115)")
```
The frontend tries to reach the token endpoint by this url: http://127.0.0.1:8081/MY_APP_BACKEND_PROTOCOL://MY_APP_BACKEND_HOST/token

My current docker-compose.yml:
```yaml
services:
  # frontend logic
  frontend:
    container_name: frontend
    image: ghcr.io/joaovitoriasilva/endurain/frontend:latest
    environment:
      - MY_APP_BACKEND_PROTOCOL=http
      - MY_APP_BACKEND_HOST=localhost:81
      - VITE_BACKEND_PROTOCOL=http # http or https, default is http
      - VITE_BACKEND_HOST=localhost:98 # api host or local ip (example: 192.168.1.10:98), default is localhost:98
    # Configure volume if you want to edit the code locally by clomming the repo
#    volumes:
#      - secret/endurain/frontend/app:/app
    ports:
      - "8081:80" # frontend port, change per your needs
    restart: unless-stopped
    
  # API logic
  backend:
    container_name: backend
    image: ghcr.io/joaovitoriasilva/endurain/backend:latest
    environment:
      - DB_PASSWORD=secret
      - SECRET_KEY=secret # openssl rand -hex 32
      - STRAVA_CLIENT_ID=secret
      - STRAVA_CLIENT_SECRET=secret
      - STRAVA_AUTH_CODE=secret
      - GEOCODES_MAPS_API=secret
      - FRONTEND_PROTOCOL=http # default is http
      - FRONTEND_HOST=frontend:8081 # frontend host or local ip (example: 192.168.1.10:8080), default is frontend:8080
    ports:
      - "98:80" # API port, change per your needs
    volumes:
#      - secret/endurain/backend/app:/app # Configure volume if you want to edit the code locally by cloning the repo and comment next line
      - secret/endurain/backend/user_images:/app/user_images # necessary for user image persistence on container image updates
    depends_on:
      - mariadb
      - jaeger # optional
    restart: unless-stopped
  # mysql mariadb logic
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=endurain
      - MYSQL_USER=endurain
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    restart: unless-stopped

  # Jaeger for opentelemetry - optional
  # Jaeger is not enabled by default. If you do not need it or want it, you can remove this container
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    restart: unless-stopped

# phpmyadmin for DB manipulation - optional
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 81:80
    environment:
      - PMA_HOST=mariadb
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb
    restart: unless-stopped

networks:
  default:
    external: true
    name: backend_network
```

Can you give me an hint what I have misconfigured?

**Comment by joaovitoriasilva** [comment]
I don't see any issue. Container name is "mariadb", DB_HOST variable by default is "mariadb" and you do not change this, so it should work.

Did you create the network "backend_network"? The backend can't reach the database server by resolving name "mariadb" using internal docker methods.

I recommend also changing FRONTEND_HOST=frontend:8081 to FRONTEND_HOST=localhost:8081 to be inline with the rest of the configuration.

Jaeger and phpmyadmin are optional, you can discard them.

You can also delete the following lines:
      - VITE_BACKEND_PROTOCOL=http # http or https, default is http
      - VITE_BACKEND_HOST=localhost:98 
I just checked and the docker compose file example as a typo. The variables should be "MY_APP_*" like stated in the README file. Fixed now, thanks for making me aware of it.

For reference here is my test env docker compose file:
```
services:
  # frontend logic
  frontend:
    container_name: frontend
    image: ghcr.io/joaovitoriasilva/endurain/frontend:latest
    environment:
      - MY_APP_BACKEND_PROTOCOL=http # http or https, default is http
      - MY_APP_BACKEND_HOST=localhost:98 # api host or local ip (example: 192.168.1.10:98), default is localhost:98
    # Configure volume if you want to edit the code locally by clomming the repo
    #volumes:
    #  - <local_path>/endurain/frontend:/app
    ports:
      - "8080:80" # frontend port, change per your needs
    restart: unless-stopped
    
  # API logic
  backend:
    container_name: backend
    image: ghcr.io/joaovitoriasilva/endurain/backend:latest
    environment:
      - DB_PASSWORD=secret
      - SECRET_KEY=secret
      - GEOCODES_MAPS_API=secret
      - FRONTEND_PROTOCOL=http # default is http
      - FRONTEND_HOST=localhost:8080 # frontend host or local ip (example: 192.168.1.10:8080), default is frontend:8080
    ports:
      - "98:80" # API port, change per your needs
    volumes:
    #  - secret/GitHub/endurain/backend/app:/app # Configure volume if you want to edit the code locally by cloning the repo and comment next line
      - secret/containers/endurain/backend/user_images:/app/user_images # necessary for user image persistence on container image updates
    depends_on:
      - mariadb
    restart: unless-stopped
  
  # mysql mariadb logic
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=endurain
      - MYSQL_USER=endurain
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - secret/containers/mariadb:/var/lib/mysql
    restart: unless-stopped

# phpmyadmin for DB manipulation - optional
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 82:80
    environment:
      - PMA_HOST=mariadb
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb
    restart: unless-stopped

networks:
  default:
    external: true
    name: backend_network
```
